// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upbwbaplcaudtxboouyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYndiYXBsY2F1ZHR4Ym9vdXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzYwNTYsImV4cCI6MjA1OTU1MjA1Nn0.sP0uWvgAMrDvgxn28IOmCZeEp6_VAH0zH_798u_qcxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);